name: Update badges
on:
  schedule:
    # Runs at 12:30am UTC
    - cron: '00 30 * * *'
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: lperez
